"""Domains Lambda handler."""

import logging

import boto3

from shared.auth import get_org_id
from shared.dynamo import get_item, put_item, update_item, delete_item, query
from shared.models import domain_keys, domain_gsi1, now_iso
from shared.quotas import check_quota, decrement_usage, increment_usage
from shared.pagination import get_pagination_params, decode_page_token, paginated_response
from shared.response import success, created, bad_request, not_found, no_content, error
from shared.ulid import generate_ulid
from shared.validation import parse_body, require_fields

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

_sesv2 = None


def _get_sesv2():
    global _sesv2
    if _sesv2 is None:
        _sesv2 = boto3.client("sesv2")
    return _sesv2


DOMAIN_FIELDS = [
    "id", "domain", "status", "mx_verified", "spf_verified", "dkim_verified",
    "dmarc_verified", "dns_records", "catch_all_inbox_id",
    "created_at", "verified_at", "updated_at",
]


def _filter_domain(item: dict) -> dict:
    return {k: item[k] for k in DOMAIN_FIELDS if k in item}


def _create_ses_identity(domain: str) -> list[str]:
    """Create a SES email identity for ``domain`` and return the DKIM tokens.

    If the identity already exists (user re-registers) we fetch the existing
    tokens instead. Raises on any other SES error so the caller can surface it.
    """
    sesv2 = _get_sesv2()
    try:
        resp = sesv2.create_email_identity(EmailIdentity=domain)
        return list(resp.get("DkimAttributes", {}).get("Tokens", []))
    except sesv2.exceptions.AlreadyExistsException:
        resp = sesv2.get_email_identity(EmailIdentity=domain)
        return list(resp.get("DkimAttributes", {}).get("Tokens", []))


def _generate_dns_records(domain: str, dkim_tokens: list[str]) -> dict:
    """Build the DNS record templates the user must publish. ``dkim_tokens``
    comes straight from SES and produces the real ``<token>.dkim.amazonses.com``
    CNAMEs SES will look for during verification."""
    return {
        "mx": {
            "type": "MX",
            "name": domain,
            "value": "10 inbound-smtp.us-east-1.amazonaws.com",
            "ttl": 1800,
        },
        "spf": {
            "type": "TXT",
            "name": domain,
            "value": "v=spf1 include:amazonses.com ~all",
            "ttl": 3600,
        },
        "dkim": [
            {
                "type": "CNAME",
                "name": f"{token}._domainkey.{domain}",
                "value": f"{token}.dkim.amazonses.com",
                "ttl": 1800,
            }
            for token in dkim_tokens
        ],
        "dmarc": {
            "type": "TXT",
            "name": f"_dmarc.{domain}",
            "value": f"v=DMARC1; p=quarantine; rua=mailto:dmarc@{domain}",
            "ttl": 3600,
        },
    }


def _generate_zone_file(domain: str, dns_records: dict) -> str:
    """Generate a BIND-format zone file from DNS records."""
    lines = [
        f"; Zone file for {domain}",
        f"; Generated by FreeMail",
        f"$ORIGIN {domain}.",
        f"$TTL 3600",
        "",
    ]

    mx = dns_records["mx"]
    lines.append(f"{mx['name']}.    {mx['ttl']}    IN    MX    {mx['value']}")
    lines.append("")

    spf = dns_records["spf"]
    lines.append(f'{spf["name"]}.    {spf["ttl"]}    IN    TXT    "{spf["value"]}"')
    lines.append("")

    for dkim in dns_records["dkim"]:
        lines.append(f'{dkim["name"]}.    {dkim["ttl"]}    IN    CNAME    {dkim["value"]}.')
    lines.append("")

    dmarc = dns_records["dmarc"]
    lines.append(f'{dmarc["name"]}.    {dmarc["ttl"]}    IN    TXT    "{dmarc["value"]}"')

    return "\n".join(lines)


def _list_domains(org_id: str, event: dict) -> dict:
    """List domains for an org."""
    limit, page_token, ascending = get_pagination_params(event)
    start_key = decode_page_token(page_token)

    items, last_key = query(
        pk=f"ORG#{org_id}",
        sk_prefix="DOMAIN#",
        limit=limit,
        ascending=ascending,
        exclusive_start_key=start_key,
    )
    filtered = [_filter_domain(i) for i in items]
    return success(paginated_response(filtered, last_key))


def _get_domain(org_id: str, domain_id: str) -> dict:
    """Get a single domain."""
    keys = domain_keys(org_id, domain_id)
    item = get_item(keys["PK"], keys["SK"])
    if not item:
        return not_found("Domain")
    return success(_filter_domain(item))


def _create_domain(org_id: str, body: dict) -> dict:
    """Create a new domain, register it with SES, and return real DKIM tokens."""
    quota_error = check_quota(org_id, "domains")
    if quota_error:
        return quota_error

    err = require_fields(body, ["domain"])
    if err:
        return bad_request(err)

    domain_name = body["domain"].strip().lower()
    if not domain_name or "." not in domain_name:
        return bad_request("domain must be a fully-qualified domain name")

    try:
        dkim_tokens = _create_ses_identity(domain_name)
    except Exception as e:
        logger.exception("SES create_email_identity failed for %s", domain_name)
        return error(
            "SES_ERROR",
            f"Could not register {domain_name} with SES: {e}",
            502,
        )

    if not dkim_tokens:
        return error(
            "SES_ERROR",
            "SES did not return DKIM tokens. Please retry or contact support.",
            502,
        )

    domain_id = generate_ulid()
    now = now_iso()
    dns_records = _generate_dns_records(domain_name, dkim_tokens)

    item = {
        **domain_keys(org_id, domain_id),
        **domain_gsi1(domain_name, domain_id),
        "id": domain_id,
        "org_id": org_id,
        "domain": domain_name,
        "status": "pending",
        "dns_records": dns_records,
        "dkim_tokens": dkim_tokens,
        "catch_all_inbox_id": "",
        "created_at": now,
        "updated_at": now,
    }
    put_item(item)
    increment_usage(org_id, "domains")
    return created(_filter_domain(item))


def _update_domain(org_id: str, domain_id: str, body: dict) -> dict:
    """Update domain fields."""
    keys = domain_keys(org_id, domain_id)
    existing = get_item(keys["PK"], keys["SK"])
    if not existing:
        return not_found("Domain")

    allowed = {"catch_all_inbox_id"}
    updates = {k: v for k, v in body.items() if k in allowed}
    if not updates:
        return bad_request("No valid fields to update")

    updates["updated_at"] = now_iso()
    updated = update_item(keys["PK"], keys["SK"], updates)
    return success(_filter_domain(updated))


def _delete_domain(org_id: str, domain_id: str) -> dict:
    """Hard delete a domain and remove the SES identity."""
    keys = domain_keys(org_id, domain_id)
    existing = get_item(keys["PK"], keys["SK"])
    if not existing:
        return not_found("Domain")

    domain_name = existing.get("domain", "")
    if domain_name:
        try:
            _get_sesv2().delete_email_identity(EmailIdentity=domain_name)
        except Exception:
            # Log but don't block deletion -- the SES identity may already be
            # gone or may need manual cleanup. The DynamoDB record is the
            # source of truth for whether the domain is "registered".
            logger.exception("SES delete_email_identity failed for %s", domain_name)

    delete_item(keys["PK"], keys["SK"])
    decrement_usage(org_id, "domains")
    return no_content()


def _verify_domain(org_id: str, domain_id: str) -> dict:
    """Check SES for the current verification state of the domain.

    SES performs DKIM verification asynchronously once DNS records propagate.
    This endpoint polls SES and updates the stored status accordingly.
    """
    keys = domain_keys(org_id, domain_id)
    existing = get_item(keys["PK"], keys["SK"])
    if not existing:
        return not_found("Domain")

    domain_name = existing["domain"]
    try:
        resp = _get_sesv2().get_email_identity(EmailIdentity=domain_name)
    except Exception as e:
        logger.exception("SES get_email_identity failed for %s", domain_name)
        return error(
            "SES_ERROR",
            f"Could not query SES for {domain_name}: {e}",
            502,
        )

    verified_for_sending = bool(resp.get("VerifiedForSendingStatus", False))
    dkim_status = resp.get("DkimAttributes", {}).get("Status", "NOT_STARTED")

    now = now_iso()
    updates: dict = {"updated_at": now}
    if verified_for_sending and dkim_status == "SUCCESS":
        updates["status"] = "verified"
        updates["dkim_verified"] = True
        updates["spf_verified"] = True
        updates["mx_verified"] = True
        if not existing.get("verified_at"):
            updates["verified_at"] = now
    elif dkim_status in ("PENDING", "NOT_STARTED"):
        updates["status"] = "verifying"
        updates["dkim_verified"] = False
    else:  # FAILED, TEMPORARY_FAILURE, etc.
        updates["status"] = "failed"
        updates["dkim_verified"] = False

    updated = update_item(keys["PK"], keys["SK"], updates)
    return success(_filter_domain(updated))


def _zone_file(org_id: str, domain_id: str) -> dict:
    """Return BIND-format zone file."""
    keys = domain_keys(org_id, domain_id)
    item = get_item(keys["PK"], keys["SK"])
    if not item:
        return not_found("Domain")

    zone = _generate_zone_file(item["domain"], item["dns_records"])
    return {
        "statusCode": 200,
        "headers": {"Content-Type": "text/dns"},
        "body": zone,
    }


def handler(event, context):
    """Route domains requests."""
    method = event.get("httpMethod", "")
    path = event.get("path", "")
    params = event.get("pathParameters") or {}
    domain_id = params.get("id", "")
    org_id = get_org_id(event)
    body = parse_body(event)

    # Sub-routes
    if path.endswith("/verify") and method == "POST":
        return _verify_domain(org_id, domain_id)
    if path.endswith("/zone-file") and method == "GET":
        return _zone_file(org_id, domain_id)

    if method == "GET":
        if domain_id:
            return _get_domain(org_id, domain_id)
        return _list_domains(org_id, event)

    if method == "POST":
        return _create_domain(org_id, body)

    if method == "PATCH":
        return _update_domain(org_id, domain_id, body)

    if method == "DELETE":
        return _delete_domain(org_id, domain_id)

    return bad_request("Unsupported method")
