"""Domains Lambda handler."""

from shared.auth import get_org_id
from shared.dynamo import get_item, put_item, update_item, delete_item, query
from shared.models import domain_keys, domain_gsi1, now_iso
from shared.pagination import get_pagination_params, decode_page_token, paginated_response
from shared.response import success, created, bad_request, not_found, no_content
from shared.ulid import generate_ulid
from shared.validation import parse_body, require_fields


def _generate_dns_records(domain: str) -> dict:
    """Generate DNS records required for email setup."""
    return {
        "mx": {
            "type": "MX",
            "name": domain,
            "value": "10 inbound-smtp.us-east-1.amazonaws.com",
            "ttl": 3600,
        },
        "spf": {
            "type": "TXT",
            "name": domain,
            "value": "v=spf1 include:amazonses.com ~all",
            "ttl": 3600,
        },
        "dkim": [
            {
                "type": "CNAME",
                "name": f"s{i}._domainkey.{domain}",
                "value": f"s{i}.dkim.victorymail.dev",
                "ttl": 3600,
            }
            for i in range(1, 4)
        ],
        "dmarc": {
            "type": "TXT",
            "name": f"_dmarc.{domain}",
            "value": "v=DMARC1; p=quarantine; rua=mailto:dmarc@victorymail.dev",
            "ttl": 3600,
        },
    }


def _generate_zone_file(domain: str, dns_records: dict) -> str:
    """Generate a BIND-format zone file from DNS records."""
    lines = [
        f"; Zone file for {domain}",
        f"; Generated by FreeMail",
        f"$ORIGIN {domain}.",
        f"$TTL 3600",
        "",
    ]

    mx = dns_records["mx"]
    lines.append(f"{mx['name']}.    {mx['ttl']}    IN    MX    {mx['value']}")
    lines.append("")

    spf = dns_records["spf"]
    lines.append(f'{spf["name"]}.    {spf["ttl"]}    IN    TXT    "{spf["value"]}"')
    lines.append("")

    for dkim in dns_records["dkim"]:
        lines.append(f'{dkim["name"]}.    {dkim["ttl"]}    IN    CNAME    {dkim["value"]}.')
    lines.append("")

    dmarc = dns_records["dmarc"]
    lines.append(f'{dmarc["name"]}.    {dmarc["ttl"]}    IN    TXT    "{dmarc["value"]}"')

    return "\n".join(lines)


def _list_domains(org_id: str, event: dict) -> dict:
    """List domains for an org."""
    limit, page_token, ascending = get_pagination_params(event)
    start_key = decode_page_token(page_token)

    items, last_key = query(
        pk=f"ORG#{org_id}",
        sk_prefix="DOMAIN#",
        limit=limit,
        ascending=ascending,
        exclusive_start_key=start_key,
    )
    return success(paginated_response(items, last_key))


def _get_domain(org_id: str, domain_id: str) -> dict:
    """Get a single domain."""
    keys = domain_keys(org_id, domain_id)
    item = get_item(keys["PK"], keys["SK"])
    if not item:
        return not_found("Domain")
    return success(item)


def _create_domain(org_id: str, body: dict) -> dict:
    """Create a new domain."""
    err = require_fields(body, ["domain"])
    if err:
        return bad_request(err)

    domain_name = body["domain"]
    domain_id = generate_ulid()
    now = now_iso()
    dns_records = _generate_dns_records(domain_name)

    item = {
        **domain_keys(org_id, domain_id),
        **domain_gsi1(domain_name, domain_id),
        "id": domain_id,
        "org_id": org_id,
        "domain": domain_name,
        "status": "pending",
        "dns_records": dns_records,
        "catch_all_inbox_id": "",
        "created_at": now,
        "updated_at": now,
    }
    put_item(item)
    return created(item)


def _update_domain(org_id: str, domain_id: str, body: dict) -> dict:
    """Update domain fields."""
    keys = domain_keys(org_id, domain_id)
    existing = get_item(keys["PK"], keys["SK"])
    if not existing:
        return not_found("Domain")

    allowed = {"catch_all_inbox_id"}
    updates = {k: v for k, v in body.items() if k in allowed}
    if not updates:
        return bad_request("No valid fields to update")

    updates["updated_at"] = now_iso()
    updated = update_item(keys["PK"], keys["SK"], updates)
    return success(updated)


def _delete_domain(org_id: str, domain_id: str) -> dict:
    """Hard delete a domain."""
    keys = domain_keys(org_id, domain_id)
    existing = get_item(keys["PK"], keys["SK"])
    if not existing:
        return not_found("Domain")

    delete_item(keys["PK"], keys["SK"])
    return no_content()


def _verify_domain(org_id: str, domain_id: str) -> dict:
    """Start domain verification (sets status to verifying)."""
    keys = domain_keys(org_id, domain_id)
    existing = get_item(keys["PK"], keys["SK"])
    if not existing:
        return not_found("Domain")

    updates = {"status": "verifying", "updated_at": now_iso()}
    updated = update_item(keys["PK"], keys["SK"], updates)
    return success(updated)


def _zone_file(org_id: str, domain_id: str) -> dict:
    """Return BIND-format zone file."""
    keys = domain_keys(org_id, domain_id)
    item = get_item(keys["PK"], keys["SK"])
    if not item:
        return not_found("Domain")

    zone = _generate_zone_file(item["domain"], item["dns_records"])
    return {
        "statusCode": 200,
        "headers": {"Content-Type": "text/dns"},
        "body": zone,
    }


def handler(event, context):
    """Route domains requests."""
    method = event.get("httpMethod", "")
    path = event.get("path", "")
    params = event.get("pathParameters") or {}
    domain_id = params.get("id", "")
    org_id = get_org_id(event)
    body = parse_body(event)

    # Sub-routes
    if path.endswith("/verify") and method == "POST":
        return _verify_domain(org_id, domain_id)
    if path.endswith("/zone-file") and method == "GET":
        return _zone_file(org_id, domain_id)

    if method == "GET":
        if domain_id:
            return _get_domain(org_id, domain_id)
        return _list_domains(org_id, event)

    if method == "POST":
        return _create_domain(org_id, body)

    if method == "PATCH":
        return _update_domain(org_id, domain_id, body)

    if method == "DELETE":
        return _delete_domain(org_id, domain_id)

    return bad_request("Unsupported method")
